from datagen.utils.minecraft.identifier import Identifier
from datagen.utils.repr.attribute import Attribute

class Attributes():
    ZOMBIE_SPAWN_REINFORCEMENTS = Attribute(Identifier.of('minecraft:zombie.spawn_reinforcements'))
    GENERIC_ATTACK_SPEED = Attribute(Identifier.of('minecraft:generic.attack_speed'))
    GENERIC_JUMP_STRENGTH = Attribute(Identifier.of('minecraft:generic.jump_strength'))
    PLAYER_ENTITY_INTERACTION_RANGE = Attribute(Identifier.of('minecraft:player.entity_interaction_range'))
    GENERIC_SAFE_FALL_DISTANCE = Attribute(Identifier.of('minecraft:generic.safe_fall_distance'))
    GENERIC_FALL_DAMAGE_MULTIPLIER = Attribute(Identifier.of('minecraft:generic.fall_damage_multiplier'))
    GENERIC_WATER_MOVEMENT_EFFICIENCY = Attribute(Identifier.of('minecraft:generic.water_movement_efficiency'))
    GENERIC_ATTACK_DAMAGE = Attribute(Identifier.of('minecraft:generic.attack_damage'))
    GENERIC_EXPLOSION_KNOCKBACK_RESISTANCE = Attribute(Identifier.of('minecraft:generic.explosion_knockback_resistance'))
    PLAYER_SNEAKING_SPEED = Attribute(Identifier.of('minecraft:player.sneaking_speed'))
    PLAYER_BLOCK_BREAK_SPEED = Attribute(Identifier.of('minecraft:player.block_break_speed'))
    PLAYER_SWEEPING_DAMAGE_RATIO = Attribute(Identifier.of('minecraft:player.sweeping_damage_ratio'))
    PLAYER_BLOCK_INTERACTION_RANGE = Attribute(Identifier.of('minecraft:player.block_interaction_range'))
    GENERIC_SCALE = Attribute(Identifier.of('minecraft:generic.scale'))
    GENERIC_ARMOR = Attribute(Identifier.of('minecraft:generic.armor'))
    GENERIC_MAX_ABSORPTION = Attribute(Identifier.of('minecraft:generic.max_absorption'))
    GENERIC_KNOCKBACK_RESISTANCE = Attribute(Identifier.of('minecraft:generic.knockback_resistance'))
    GENERIC_MOVEMENT_EFFICIENCY = Attribute(Identifier.of('minecraft:generic.movement_efficiency'))
    GENERIC_ATTACK_KNOCKBACK = Attribute(Identifier.of('minecraft:generic.attack_knockback'))
    GENERIC_LUCK = Attribute(Identifier.of('minecraft:generic.luck'))
    GENERIC_MOVEMENT_SPEED = Attribute(Identifier.of('minecraft:generic.movement_speed'))
    GENERIC_FLYING_SPEED = Attribute(Identifier.of('minecraft:generic.flying_speed'))
    GENERIC_GRAVITY = Attribute(Identifier.of('minecraft:generic.gravity'))
    PLAYER_SUBMERGED_MINING_SPEED = Attribute(Identifier.of('minecraft:player.submerged_mining_speed'))
    PLAYER_MINING_EFFICIENCY = Attribute(Identifier.of('minecraft:player.mining_efficiency'))
    GENERIC_MAX_HEALTH = Attribute(Identifier.of('minecraft:generic.max_health'))
    GENERIC_ARMOR_TOUGHNESS = Attribute(Identifier.of('minecraft:generic.armor_toughness'))
    GENERIC_FOLLOW_RANGE = Attribute(Identifier.of('minecraft:generic.follow_range'))
    GENERIC_OXYGEN_BONUS = Attribute(Identifier.of('minecraft:generic.oxygen_bonus'))
    GENERIC_STEP_HEIGHT = Attribute(Identifier.of('minecraft:generic.step_height'))
    GENERIC_BURNING_TIME = Attribute(Identifier.of('minecraft:generic.burning_time'))
