from datagen.utils.minecraft.identifier import Identifier
from datagen.utils.repr.enchantment import Enchantment

class Enchantments():
    EFFICIENCY = Enchantment(Identifier.of("minecraft:efficiency"))
    SWEEPING_EDGE = Enchantment(Identifier.of("minecraft:sweeping_edge"))
    LOOTING = Enchantment(Identifier.of("minecraft:looting"))
    QUICK_CHARGE = Enchantment(Identifier.of("minecraft:quick_charge"))
    SILK_TOUCH = Enchantment(Identifier.of("minecraft:silk_touch"))
    SOUL_SPEED = Enchantment(Identifier.of("minecraft:soul_speed"))
    BREACH = Enchantment(Identifier.of("minecraft:breach"))
    DENSITY = Enchantment(Identifier.of("minecraft:density"))
    FLAME = Enchantment(Identifier.of("minecraft:flame"))
    FORTUNE = Enchantment(Identifier.of("minecraft:fortune"))
    AQUA_AFFINITY = Enchantment(Identifier.of("minecraft:aqua_affinity"))
    MULTISHOT = Enchantment(Identifier.of("minecraft:multishot"))
    CHANNELING = Enchantment(Identifier.of("minecraft:channeling"))
    LOYALTY = Enchantment(Identifier.of("minecraft:loyalty"))
    BINDING_CURSE = Enchantment(Identifier.of("minecraft:binding_curse"))
    PUNCH = Enchantment(Identifier.of("minecraft:punch"))
    POWER = Enchantment(Identifier.of("minecraft:power"))
    PROJECTILE_PROTECTION = Enchantment(Identifier.of("minecraft:projectile_protection"))
    SHARPNESS = Enchantment(Identifier.of("minecraft:sharpness"))
    FROST_WALKER = Enchantment(Identifier.of("minecraft:frost_walker"))
    FIRE_PROTECTION = Enchantment(Identifier.of("minecraft:fire_protection"))
    IMPALING = Enchantment(Identifier.of("minecraft:impaling"))
    LUCK_OF_THE_SEA = Enchantment(Identifier.of("minecraft:luck_of_the_sea"))
    RIPTIDE = Enchantment(Identifier.of("minecraft:riptide"))
    MENDING = Enchantment(Identifier.of("minecraft:mending"))
    PROTECTION = Enchantment(Identifier.of("minecraft:protection"))
    RESPIRATION = Enchantment(Identifier.of("minecraft:respiration"))
    PIERCING = Enchantment(Identifier.of("minecraft:piercing"))
    FEATHER_FALLING = Enchantment(Identifier.of("minecraft:feather_falling"))
    SWIFT_SNEAK = Enchantment(Identifier.of("minecraft:swift_sneak"))
    UNBREAKING = Enchantment(Identifier.of("minecraft:unbreaking"))
    FIRE_ASPECT = Enchantment(Identifier.of("minecraft:fire_aspect"))
    LURE = Enchantment(Identifier.of("minecraft:lure"))
    SMITE = Enchantment(Identifier.of("minecraft:smite"))
    KNOCKBACK = Enchantment(Identifier.of("minecraft:knockback"))
    DEPTH_STRIDER = Enchantment(Identifier.of("minecraft:depth_strider"))
    WIND_BURST = Enchantment(Identifier.of("minecraft:wind_burst"))
    INFINITY = Enchantment(Identifier.of("minecraft:infinity"))
    VANISHING_CURSE = Enchantment(Identifier.of("minecraft:vanishing_curse"))
    BANE_OF_ARTHROPODS = Enchantment(Identifier.of("minecraft:bane_of_arthropods"))
    BLAST_PROTECTION = Enchantment(Identifier.of("minecraft:blast_protection"))
    THORNS = Enchantment(Identifier.of("minecraft:thorns"))
