from datagen.utils.minecraft.identifier import Identifier
from datagen.utils.repr.mob_effect import MobEffect

class MobEffects():
    CREEPER = MobEffect(Identifier.of('minecraft:creeper'))
    RHOMBUS = MobEffect(Identifier.of('minecraft:rhombus'))
    BORDER = MobEffect(Identifier.of('minecraft:border'))
    HALF_HORIZONTAL = MobEffect(Identifier.of('minecraft:half_horizontal'))
    GRADIENT_UP = MobEffect(Identifier.of('minecraft:gradient_up'))
    BRICKS = MobEffect(Identifier.of('minecraft:bricks'))
    STRIPE_LEFT = MobEffect(Identifier.of('minecraft:stripe_left'))
    TRIANGLES_BOTTOM = MobEffect(Identifier.of('minecraft:triangles_bottom'))
    SKULL = MobEffect(Identifier.of('minecraft:skull'))
    DIAGONAL_RIGHT = MobEffect(Identifier.of('minecraft:diagonal_right'))
    CROSS = MobEffect(Identifier.of('minecraft:cross'))
    DIAGONAL_UP_LEFT = MobEffect(Identifier.of('minecraft:diagonal_up_left'))
    GRADIENT = MobEffect(Identifier.of('minecraft:gradient'))
    FLOWER = MobEffect(Identifier.of('minecraft:flower'))
    HALF_HORIZONTAL_BOTTOM = MobEffect(Identifier.of('minecraft:half_horizontal_bottom'))
    HALF_VERTICAL = MobEffect(Identifier.of('minecraft:half_vertical'))
    TRIANGLE_TOP = MobEffect(Identifier.of('minecraft:triangle_top'))
    GLOBE = MobEffect(Identifier.of('minecraft:globe'))
    STRIPE_DOWNLEFT = MobEffect(Identifier.of('minecraft:stripe_downleft'))
    GUSTER = MobEffect(Identifier.of('minecraft:guster'))
    CURLY_BORDER = MobEffect(Identifier.of('minecraft:curly_border'))
    HALF_VERTICAL_RIGHT = MobEffect(Identifier.of('minecraft:half_vertical_right'))
    SQUARE_BOTTOM_LEFT = MobEffect(Identifier.of('minecraft:square_bottom_left'))
    MOJANG = MobEffect(Identifier.of('minecraft:mojang'))
    TRIANGLES_TOP = MobEffect(Identifier.of('minecraft:triangles_top'))
    PIGLIN = MobEffect(Identifier.of('minecraft:piglin'))
    SQUARE_TOP_LEFT = MobEffect(Identifier.of('minecraft:square_top_left'))
    FLOW = MobEffect(Identifier.of('minecraft:flow'))
    STRAIGHT_CROSS = MobEffect(Identifier.of('minecraft:straight_cross'))
    TRIANGLE_BOTTOM = MobEffect(Identifier.of('minecraft:triangle_bottom'))
    STRIPE_MIDDLE = MobEffect(Identifier.of('minecraft:stripe_middle'))
    STRIPE_RIGHT = MobEffect(Identifier.of('minecraft:stripe_right'))
    DIAGONAL_UP_RIGHT = MobEffect(Identifier.of('minecraft:diagonal_up_right'))
    STRIPE_DOWNRIGHT = MobEffect(Identifier.of('minecraft:stripe_downright'))
    SQUARE_BOTTOM_RIGHT = MobEffect(Identifier.of('minecraft:square_bottom_right'))
    STRIPE_TOP = MobEffect(Identifier.of('minecraft:stripe_top'))
    DIAGONAL_LEFT = MobEffect(Identifier.of('minecraft:diagonal_left'))
    STRIPE_BOTTOM = MobEffect(Identifier.of('minecraft:stripe_bottom'))
    STRIPE_CENTER = MobEffect(Identifier.of('minecraft:stripe_center'))
    SMALL_STRIPES = MobEffect(Identifier.of('minecraft:small_stripes'))
    BASE = MobEffect(Identifier.of('minecraft:base'))
    SQUARE_TOP_RIGHT = MobEffect(Identifier.of('minecraft:square_top_right'))
    CIRCLE = MobEffect(Identifier.of('minecraft:circle'))
