from datagen.utils.minecraft.identifier import Identifier
from datagen.utils.repr.status_effect import StatusEffect

class StatusEffects():
    INSTANT_HEALTH = StatusEffect(Identifier.of('minecraft:instant_health'))
    WATER_BREATHING = StatusEffect(Identifier.of('minecraft:water_breathing'))
    INVISIBILITY = StatusEffect(Identifier.of('minecraft:invisibility'))
    RESISTANCE = StatusEffect(Identifier.of('minecraft:resistance'))
    UNLUCK = StatusEffect(Identifier.of('minecraft:unluck'))
    BLINDNESS = StatusEffect(Identifier.of('minecraft:blindness'))
    HASTE = StatusEffect(Identifier.of('minecraft:haste'))
    POISON = StatusEffect(Identifier.of('minecraft:poison'))
    SLOWNESS = StatusEffect(Identifier.of('minecraft:slowness'))
    HUNGER = StatusEffect(Identifier.of('minecraft:hunger'))
    SLOW_FALLING = StatusEffect(Identifier.of('minecraft:slow_falling'))
    WEAVING = StatusEffect(Identifier.of('minecraft:weaving'))
    FIRE_RESISTANCE = StatusEffect(Identifier.of('minecraft:fire_resistance'))
    SATURATION = StatusEffect(Identifier.of('minecraft:saturation'))
    RAID_OMEN = StatusEffect(Identifier.of('minecraft:raid_omen'))
    JUMP_BOOST = StatusEffect(Identifier.of('minecraft:jump_boost'))
    MINING_FATIGUE = StatusEffect(Identifier.of('minecraft:mining_fatigue'))
    DOLPHINS_GRACE = StatusEffect(Identifier.of('minecraft:dolphins_grace'))
    HEALTH_BOOST = StatusEffect(Identifier.of('minecraft:health_boost'))
    REGENERATION = StatusEffect(Identifier.of('minecraft:regeneration'))
    CONDUIT_POWER = StatusEffect(Identifier.of('minecraft:conduit_power'))
    SPEED = StatusEffect(Identifier.of('minecraft:speed'))
    LUCK = StatusEffect(Identifier.of('minecraft:luck'))
    BAD_OMEN = StatusEffect(Identifier.of('minecraft:bad_omen'))
    TRIAL_OMEN = StatusEffect(Identifier.of('minecraft:trial_omen'))
    STRENGTH = StatusEffect(Identifier.of('minecraft:strength'))
    DARKNESS = StatusEffect(Identifier.of('minecraft:darkness'))
    HERO_OF_THE_VILLAGE = StatusEffect(Identifier.of('minecraft:hero_of_the_village'))
    LEVITATION = StatusEffect(Identifier.of('minecraft:levitation'))
    INSTANT_DAMAGE = StatusEffect(Identifier.of('minecraft:instant_damage'))
    OOZING = StatusEffect(Identifier.of('minecraft:oozing'))
    WEAKNESS = StatusEffect(Identifier.of('minecraft:weakness'))
    NAUSEA = StatusEffect(Identifier.of('minecraft:nausea'))
    WIND_CHARGED = StatusEffect(Identifier.of('minecraft:wind_charged'))
    WITHER = StatusEffect(Identifier.of('minecraft:wither'))
    ABSORPTION = StatusEffect(Identifier.of('minecraft:absorption'))
    GLOWING = StatusEffect(Identifier.of('minecraft:glowing'))
    INFESTED = StatusEffect(Identifier.of('minecraft:infested'))
    NIGHT_VISION = StatusEffect(Identifier.of('minecraft:night_vision'))
