from datagen.utils.minecraft.identifier import Identifier
from datagen.utils.repr.structure import Structure

class Structures():
    DESERT_PYRAMID = Structure(Identifier.of('minecraft:desert_pyramid'))
    RUINED_PORTAL_SWAMP = Structure(Identifier.of('minecraft:ruined_portal_swamp'))
    VILLAGE_TAIGA = Structure(Identifier.of('minecraft:village_taiga'))
    NETHER_FOSSIL = Structure(Identifier.of('minecraft:nether_fossil'))
    BASTION_REMNANT = Structure(Identifier.of('minecraft:bastion_remnant'))
    PILLAGER_OUTPOST = Structure(Identifier.of('minecraft:pillager_outpost'))
    TRIAL_CHAMBERS = Structure(Identifier.of('minecraft:trial_chambers'))
    SHIPWRECK = Structure(Identifier.of('minecraft:shipwreck'))
    JUNGLE_PYRAMID = Structure(Identifier.of('minecraft:jungle_pyramid'))
    MINESHAFT_MESA = Structure(Identifier.of('minecraft:mineshaft_mesa'))
    RUINED_PORTAL_JUNGLE = Structure(Identifier.of('minecraft:ruined_portal_jungle'))
    SWAMP_HUT = Structure(Identifier.of('minecraft:swamp_hut'))
    OCEAN_RUIN_WARM = Structure(Identifier.of('minecraft:ocean_ruin_warm'))
    VILLAGE_PLAINS = Structure(Identifier.of('minecraft:village_plains'))
    RUINED_PORTAL = Structure(Identifier.of('minecraft:ruined_portal'))
    BURIED_TREASURE = Structure(Identifier.of('minecraft:buried_treasure'))
    MANSION = Structure(Identifier.of('minecraft:mansion'))
    RUINED_PORTAL_DESERT = Structure(Identifier.of('minecraft:ruined_portal_desert'))
    END_CITY = Structure(Identifier.of('minecraft:end_city'))
    MINESHAFT = Structure(Identifier.of('minecraft:mineshaft'))
    MONUMENT = Structure(Identifier.of('minecraft:monument'))
    IGLOO = Structure(Identifier.of('minecraft:igloo'))
    RUINED_PORTAL_OCEAN = Structure(Identifier.of('minecraft:ruined_portal_ocean'))
    RUINED_PORTAL_MOUNTAIN = Structure(Identifier.of('minecraft:ruined_portal_mountain'))
    FORTRESS = Structure(Identifier.of('minecraft:fortress'))
    TRAIL_RUINS = Structure(Identifier.of('minecraft:trail_ruins'))
    VILLAGE_SAVANNA = Structure(Identifier.of('minecraft:village_savanna'))
    RUINED_PORTAL_NETHER = Structure(Identifier.of('minecraft:ruined_portal_nether'))
    SHIPWRECK_BEACHED = Structure(Identifier.of('minecraft:shipwreck_beached'))
    STRONGHOLD = Structure(Identifier.of('minecraft:stronghold'))
    ANCIENT_CITY = Structure(Identifier.of('minecraft:ancient_city'))
    VILLAGE_DESERT = Structure(Identifier.of('minecraft:village_desert'))
    OCEAN_RUIN_COLD = Structure(Identifier.of('minecraft:ocean_ruin_cold'))
    VILLAGE_SNOWY = Structure(Identifier.of('minecraft:village_snowy'))
